### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by chessboards** [Ceebox/cbLang#1]
use regex m8

pls

;(

**Comment by epsseniyer** [comment]
regex is bad

**Comment by Moosems** [comment]
Says who? Regex was added for good reason

**Comment by Oddsie** [comment]
it's bad

**Comment by Moosems** [comment]
Can you please give reasons why?

**Comment by Oddsie** [comment]
because its annoying and unreadable and alos hard

**Comment by Moosems** [comment]
Annoying how, unreadable yes but just do some test cases, and hard how?

**Comment by Oddsie** [comment]
Very confusing to work with and learn.

**Comment by Moosems** [comment]
Not exactly. Just sit down with a guide and you'll figure it out pretty fast

**Comment by Oddsie** [comment]
I've tried.

**Comment by Moosems** [comment]
What was your problem?

**Comment by Oddsie** [comment]
As I said, confusing and unreadable.

**Comment by Moosems** [comment]
To each his own

**Comment by Oddsie** [comment]
huh?

**Comment by Moosems** [comment]
I find it easy to read and pretty understandable

**Comment by Oddsie** [comment]
well not for me

**Comment by Moosems** [comment]
But that doesn't make it bad. Many people can't read code but that doesn't make coding bad

**Comment by Oddsie** [comment]
yes but it makes regex bad.

**Comment by Moosems** [comment]
So coding is bad?

**Comment by Oddsie** [comment]
bruh, if it is why would i be on github.

**Comment by Moosems** [comment]
I'm just pointing out that your logic doesn't make sense. Regex has its use cases and just because you don't like it doesn't mean its bad.

**Comment by Oddsie** [comment]
i meant in my own opinion its bad. someone else might like it, but not me.

**Comment by chessboards** [comment]
regex for the purpose of language parsing has downsides so use antlr4

**Comment by ConnorTippets** [comment]
what the hell is this discussion LMAOO its literally just "regex is bad" "why" "cuz i said its bad" over the course of 20 messages
