### ISSUE TITLE
No Mac Download

### ISSUE THREAD

**Issue by Moosems** [Ceebox/cbLang#2]
Could you add a mac download?

**Comment by UlysseBerra** [comment]
Same here with Linux!

**Comment by Ceebox** [comment]
Hey, this is written in Python so if you download it and install the dependencies then it should work fine on Mac/Linux (I hope, there might be some errors from some tweaking I did).

**Comment by UlysseBerra** [comment]
Indeed, that's what I did for now!

**Comment by Moosems** [comment]
> Hey, this is written in Python so if you download it and install the dependencies then it should work fine on Mac/Linux (I hope, there might be some errors from some tweaking I did).

Are there any windows specific dependencies like win32?

**Comment by asdu5asg6da8sjd** [comment]
@Moosems I don't think so.

**Comment by Moosems** [comment]
> Hey, this is written in Python so if you download it and install the dependencies then it should work fine on Mac/Linux (I hope, there might be some errors from some tweaking I did).

How could I run it without the exe? Would I use pyinstaller on any specific script or call a script for it?

**Comment by epsseniyer** [comment]
If you installed pyinstaller you can do this already

**Comment by epsseniyer** [comment]
Anyone can Close issue?

**Comment by Moosems** [comment]
I'll close for now but I might make a pr that adds mac and linux builds in the future

**Comment by asdu5asg6da8sjd** [comment]
@Moosems If you own a mac. You could use the depricated python version of the cblang compiler to compile the new version of the cblang compiler to mac.
