### ISSUE TITLE
[Suggestion] VSCode Syntax hylighting.

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [Ceebox/cbLang#7]

**Comment by Ceebox** [comment]
https://marketplace.visualstudio.com/items?itemName=aubergine5678.cblang-syntaxhighlighting
https://github.com/aubergine5678/cblang-syntaxhighlighting

@aubergine5678 has very kindly created this extension.

**Comment by asdu5asg6da8sjd** [comment]
Thank you!
